spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/laboratory_equipment_management_system?characterEncoding=UTF-8
    username: root
    password: Gzx@123
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  type-aliases-package: com.resetful.model
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
